### ISSUE TITLE
Unclear what flags are necessary, and error messages.

### ISSUE THREAD

**Issue by KevinHock** [ThreatResponse/margaritashotgun#1]
Solution: 
Change "except KeyError:" to  "except TypeError:" in workers.py

Problem:
Like in the README I tried:
ubuntu@ip-123-45-67-81:~/margaritashotgun$ margaritashotgun -s 12.34.56.78 -u ubuntu -k /home/ubuntu/margarita.pem -m /home/ubuntu/lime-3.13.0-92-generic.ko -f the_dump_52-26-35-253-mem.lime

I was missing the -d flag so in workers.py:

``` python
            log_dir = conf[0]['logging']['log_dir']
            if log_dir[-1:] != '/':
```

we get
TypeError: 'NoneType' object has no attribute '**getitem**' [1]

So I tried adding the d flag
ubuntu@ip-123-45-67-81:~/margaritashotgun$ margaritashotgun -s 12.34.56.78 -u ubuntu -k /home/ubuntu/margarita.pem -m /home/ubuntu/lime-3.13.0-92-generic.ko -f the_dump_52-26-35-253-mem.lime -d ~/logs/

In workers.py:

``` python
        try:
            log_prefix = conf[0]['logging']['prefix'] + "-"
        except KeyError:
            log_prefix = ""
```

we get
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' [2]

So I tried adding the --log_prefix option, and it worked :D Thanks for making this!

[1]
Traceback (most recent call last):
  File "/usr/local/bin/margaritashotgun", line 4, in <module>
    **import**('pkg_resources').run_script('margaritashotgun==0.3.1', 'margaritashotgun')
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 744, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1506, in run_script
  File "/usr/local/lib/python2.7/dist-packages/margaritashotgun-0.3.1-py2.7.egg/EGG-INFO/scripts/margaritashotgun", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/margaritashotgun/client.py", line 52, in run
  File "build/bdist.linux-x86_64/egg/margaritashotgun/workers.py", line 29, in **init**
TypeError: 'NoneType' object has no attribute '**getitem**'

[2]
Traceback (most recent call last):
  File "/usr/local/bin/margaritashotgun", line 4, in <module>
    **import**('pkg_resources').run_script('margaritashotgun==0.3.1', 'margaritashotgun')
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 744, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1506, in run_script
  File "/usr/local/lib/python2.7/dist-packages/margaritashotgun-0.3.1-py2.7.egg/EGG-INFO/scripts/margaritashotgun", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/margaritashotgun/client.py", line 52, in run
  File "build/bdist.linux-x86_64/egg/margaritashotgun/workers.py", line 34, in **init**
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by KevinHock** [comment]
PR here https://github.com/ThreatResponse/margaritashotgun/pull/2

**Comment by joelferrier** [comment]
Thanks for the support! PR looks good, I'll cleanup the flags a bit and update the documentation to make required flags more clear

**Comment by KevinHock** [comment]
Thanks 👍
